GET http://localhost:3000/musiksuche/atemlos

###

POST http://localhost:3000/wunschliste
Content-Type: application/json

{
    "title": "Blinding Lights",
    "artist": "The Weekend",
    "pickedToList": "Yes"
}

###

GET http://localhost:3000/wunschliste

###

DELETE http://localhost:3000/songs/5e8de2d7a460720c3c44ff65

###

PATCH  http://localhost:3000/wunschliste

{
    "title": "Blinding Lights",
    "artist": "The Weekend"
}

###

POST http://localhost:3000/dj
Content-Type: application/json

{
    "name": "Wonnerth",
    "vorname": "Philipp",
    "kuenstlerName": "DJ-P"
}

###

GET http://localhost:3000/dj
