GET http://localhost:3000/musiksuche/atemlos

###

POST http://localhost:3000/wunschliste
Content-Type: application/json

{
    "title": "Lights",
    "artist": "The Weekend",
    "pickedToList": "Yes"
}

###

GET http://localhost:3000/wunschliste

###

DELETE http://localhost:3000/songs

###

PATCH  http://localhost:3000/wunschliste/5ec54d5acc43f229289082b0
Content-Type: application/json

{
    "title": "Blinding Lights",
    "artist": "The Weekend"
}

###

PATCH  http://localhost:3000/wunschliste
Content-Type: application/json


###

POST http://localhost:3000/dj
Content-Type: application/json

{
    "name": "Wonnerth",
    "vorname": "Philipp",
    "kuenstlerName": "DJ-P"
}

###

GET http://localhost:3000/dj

###

PUT http://localhost:3000/songs/5e8e18a1f571fb0f30a864f8
Content-Type: application/json

{
    "title": "Atmelos",
    "artist": "Helene Fischer"
}